In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import pandas_profiling

In [2]:
pd.__version__

'0.25.3'

In [3]:
np.__version__

'1.18.1'

In [4]:
ind=[('California',2000),('California',2010),
     ('New York',2000),('New York',2010),
    ('Texas',2000),('Texas',2010)]
populations=[33871648,37253956,
             18976457,19378102,
             20851820,25145561]

In [5]:
pop=pd.Series(populations,index=ind)
pop

(California, 2000)    33871648
(California, 2010)    37253956
(New York, 2000)      18976457
(New York, 2010)      19378102
(Texas, 2000)         20851820
(Texas, 2010)         25145561
dtype: int64

In [6]:
pop.index

Index([('California', 2000), ('California', 2010),   ('New York', 2000),
         ('New York', 2010),      ('Texas', 2000),      ('Texas', 2010)],
      dtype='object')

In [8]:
pop[[i for i in pop.index if i[1]==2010]]

(California, 2010)    37253956
(New York, 2010)      19378102
(Texas, 2010)         25145561
dtype: int64

In [7]:
for i in pop.index:
    if i[1]==2010:
        print(i,pop[i])

('California', 2010) 37253956
('New York', 2010) 19378102
('Texas', 2010) 25145561


# BETTER WAYS TO DESIGN INDEXINGS

In [8]:
pop.index

Index([('California', 2000), ('California', 2010),   ('New York', 2000),
         ('New York', 2010),      ('Texas', 2000),      ('Texas', 2010)],
      dtype='object')

In [9]:
index=pd.MultiIndex.from_tuples(ind)
index

MultiIndex([('California', 2000),
            ('California', 2010),
            (  'New York', 2000),
            (  'New York', 2010),
            (     'Texas', 2000),
            (     'Texas', 2010)],
           )

In [11]:
pop=pop.reindex(index) # to reindex the columns
pop

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [12]:
pop['California']

2000    33871648
2010    37253956
dtype: int64

In [13]:
pop['California'][2010]

37253956

In [14]:
pop[2]

18976457

In [17]:
pop[1]

37253956

In [18]:
pop[0]

33871648

In [19]:
pop[0:3]

California  2000    33871648
            2010    37253956
New York    2000    18976457
dtype: int64

In [20]:
pop[0:6]

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [21]:
pop[0::2]

California  2000    33871648
New York    2000    18976457
Texas       2000    20851820
dtype: int64

In [26]:
pop[0::1]

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [27]:
pop[:,2010]

California    37253956
New York      19378102
Texas         25145561
dtype: int64

In [28]:
pop.ndim

1

In [15]:
pop_df=pop.unstack()
pop_df

2000      2010
California  33871648  37253956
New York    18976457  19378102
Texas       20851820  25145561

In [16]:
pop_df.ndim

2

In [31]:
se=pop_df.stack()
se

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [32]:
se.ndim

1

In [22]:
pop_df=pd.DataFrame({'Total':pop,
                    'Under18':[9267089,9284094,
                             4687374,4318033,
                             5906301,6879014]})
pop_df

Total  Under18
California 2000  33871648  9267089
           2010  37253956  9284094
New York   2000  18976457  4687374
           2010  19378102  4318033
Texas      2000  20851820  5906301
           2010  25145561  6879014

In [18]:
pop_df['Total']

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
Name: Total, dtype: int64

In [23]:
f_u18=pop_df['Under18']/pop_df['Total']
f_u18.unstack()

2000      2010
California  0.273594  0.249211
New York    0.247010  0.222831
Texas       0.283251  0.273568

# Methods of MultiIndex Creation

In [41]:
df=pd.DataFrame(np.random.rand(4,2),
               index=[['a','a','b','b'],[1,2,1,2]],
               columns=['data1','data2'])
df

data1     data2
a 1  0.870494  0.711421
  2  0.166963  0.119720
b 1  0.348870  0.140118
  2  0.699112  0.225528

In [42]:
data={('California',2000):33871648,
     ('California',2010):37253956,
     ('Texas',2000):20851820,
     ('Texas',2010):25145561,
     ('New york',2000):18976457,
     ('New York',2010):19378102}
pd.Series(data)

California  2000    33871648
            2010    37253956
Texas       2000    20851820
            2010    25145561
New york    2000    18976457
New York    2010    19378102
dtype: int64

In [43]:
pd.MultiIndex.from_arrays([['a','a','b','b'],[1,2,1,2]])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           )

In [44]:
pd.MultiIndex.from_tuples([('a',1),('a',2),('b',1),('b',2)])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           )

In [45]:
pd.MultiIndex.from_product([['a','b'],[1,2]])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           )

In [46]:
pd.MultiIndex(levels=[['a','b'],[1,2]],
             codes=[[0,0,1,1],[0,1,0,1]])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           )

In [47]:
pop.index.names=['state','year']
pop

state       year
California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

MultiIndex for Columns

In [48]:
index=pd.MultiIndex.from_product([[2013,2014],[1,2,3]],
                                names=['year','visit'])
columns=pd.MultiIndex.from_product([['Rani','Raju','Sam'],['BMI','Temp','Weight']],
                                  names=['Name','type'])

In [49]:
data=np.round(np.random.rand(6,9),2)
data

array([[0.48, 0.02, 0.79, 0.55, 0.29, 0.65, 0.14, 0.21, 0.68],
       [0.59, 0.53, 0.84, 0.84, 0.53, 0.15, 0.08, 0.29, 0.47],
       [0.28, 0.87, 0.47, 0.52, 0.23, 0.87, 0.16, 0.56, 0.6 ],
       [0.14, 0.84, 0.2 , 0.15, 0.86, 0.79, 0.5 , 0.87, 0.08],
       [0.91, 0.27, 0.78, 0.37, 0.25, 0.3 , 0.74, 1.  , 0.08],
       [0.99, 0.51, 0.07, 1.  , 0.24, 0.45, 0.75, 0.61, 0.58]])

In [50]:
data[:,::2]*=10
data

array([[4.8 , 0.02, 7.9 , 0.55, 2.9 , 0.65, 1.4 , 0.21, 6.8 ],
       [5.9 , 0.53, 8.4 , 0.84, 5.3 , 0.15, 0.8 , 0.29, 4.7 ],
       [2.8 , 0.87, 4.7 , 0.52, 2.3 , 0.87, 1.6 , 0.56, 6.  ],
       [1.4 , 0.84, 2.  , 0.15, 8.6 , 0.79, 5.  , 0.87, 0.8 ],
       [9.1 , 0.27, 7.8 , 0.37, 2.5 , 0.3 , 7.4 , 1.  , 0.8 ],
       [9.9 , 0.51, 0.7 , 1.  , 2.4 , 0.45, 7.5 , 0.61, 5.8 ]])

In [51]:
data+=37
data

array([[41.8 , 37.02, 44.9 , 37.55, 39.9 , 37.65, 38.4 , 37.21, 43.8 ],
       [42.9 , 37.53, 45.4 , 37.84, 42.3 , 37.15, 37.8 , 37.29, 41.7 ],
       [39.8 , 37.87, 41.7 , 37.52, 39.3 , 37.87, 38.6 , 37.56, 43.  ],
       [38.4 , 37.84, 39.  , 37.15, 45.6 , 37.79, 42.  , 37.87, 37.8 ],
       [46.1 , 37.27, 44.8 , 37.37, 39.5 , 37.3 , 44.4 , 38.  , 37.8 ],
       [46.9 , 37.51, 37.7 , 38.  , 39.4 , 37.45, 44.5 , 37.61, 42.8 ]])

In [52]:
#Create the DataFrame
health_data=pd.DataFrame(data,index=index,columns=columns)
health_data

Name        Rani                 Raju                Sam              
type         BMI   Temp Weight    BMI  Temp Weight   BMI   Temp Weight
year visit                                                            
2013 1      41.8  37.02   44.9  37.55  39.9  37.65  38.4  37.21   43.8
     2      42.9  37.53   45.4  37.84  42.3  37.15  37.8  37.29   41.7
     3      39.8  37.87   41.7  37.52  39.3  37.87  38.6  37.56   43.0
2014 1      38.4  37.84   39.0  37.15  45.6  37.79  42.0  37.87   37.8
     2      46.1  37.27   44.8  37.37  39.5  37.30  44.4  38.00   37.8
     3      46.9  37.51   37.7  38.00  39.4  37.45  44.5  37.61   42.8

In [53]:
health_data.to_csv("Health_Data_For_MultiIndexing.csv")

In [54]:
health_data['Rani']

type         BMI   Temp  Weight
year visit                     
2013 1      41.8  37.02    44.9
     2      42.9  37.53    45.4
     3      39.8  37.87    41.7
2014 1      38.4  37.84    39.0
     2      46.1  37.27    44.8
     3      46.9  37.51    37.7

In [55]:
health_data.iloc[1]

Name  type  
Rani  BMI       42.90
      Temp      37.53
      Weight    45.40
Raju  BMI       37.84
      Temp      42.30
      Weight    37.15
Sam   BMI       37.80
      Temp      37.29
      Weight    41.70
Name: (2013, 2), dtype: float64

In [60]:
health_data.iloc[1:2]

Name        Rani                 Raju                Sam              
type         BMI   Temp Weight    BMI  Temp Weight   BMI   Temp Weight
year visit                                                            
2013 2      42.9  37.53   45.4  37.84  42.3  37.15  37.8  37.29   41.7