In [1]:
import numpy as np
import pandas as pd

In [2]:
a=np.array([10,20,30,40,np.nan])

In [3]:
np.nan_to_num(a)

array([10., 20., 30., 40.,  0.])

In [4]:
np.nanmean(a)

25.0

In [5]:
np.nanmax(a)

40.0

In [6]:
np.nanmin(a)

10.0

In [7]:
np.nancumprod(a)

array([1.0e+01, 2.0e+02, 6.0e+03, 2.4e+05, 2.4e+05])

In [8]:
np.nancumsum(a)

array([ 10.,  30.,  60., 100., 100.])

In [9]:
np.nanargmax(a)

3

In [10]:
np.nanargmin(a)

0

In [12]:
np.nanprod(a)

240000.0

In [14]:
np.nanstd(a)

11.180339887498949

In [15]:
np.nansum(a)

100.0

In [16]:
np.nansum(a)

100.0

In [17]:
np.nanvar(a)

125.0

In [18]:
import numpy as np
import pandas as pd

In [19]:
valS1=np.array([1,None,3,4])
valS1

array([1, None, 3, 4], dtype=object)

In [20]:
valS1.dtype

dtype('O')

In [21]:
v=np.arange(12).reshape(3,4)
v

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [22]:
v.dtype

dtype('int32')

In [25]:
v[0][0]

0

In [26]:
v[0][0]="None"
v

ValueError: invalid literal for int() with base 10: 'None'

In [27]:
try:
    a='Hello2'
    print(int(a))
except NameError as ne:
    print(ne)

ValueError: invalid literal for int() with base 10: 'Hello2'

In [28]:
np.arange(1E6)

array([0.00000e+00, 1.00000e+00, 2.00000e+00, ..., 9.99997e+05,
       9.99998e+05, 9.99999e+05])

In [31]:
for dtype in['object','int','float','complex']:
    print("dtype=",dtype)
    %timeit np.arange(1E6,dtype=dtype).sum()
    print()

dtype= object
118 ms ± 11.4 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

dtype= int
3.56 ms ± 40.6 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

dtype= float
6.74 ms ± 98.4 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

dtype= complex
12 ms ± 92.4 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)



In [33]:
valS2=np.array([1,3,4,np.nan])
valS2.dtype

dtype('float64')

In [34]:
1+np.nan

nan

In [35]:
0+np.nan

nan

In [36]:
valS2.sum(),valS2.min(),valS2.min()

(nan, nan, nan)

In [40]:
import pandas as pd
pd.Series([1,np.nan,2,None])

0    1.0
1    NaN
2    2.0
3    NaN
dtype: float64

In [41]:
x=pd.Series(range(4),dtype=int)
x

0    0
1    1
2    2
3    3
dtype: int32

In [42]:
x[3]=None
x

0    0.0
1    1.0
2    2.0
3    NaN
dtype: float64

In [43]:
x.add(2)

0    2.0
1    3.0
2    4.0
3    NaN
dtype: float64

In [44]:
np.nan_to_num(x)

array([0., 1., 2., 0.])

In [45]:
np.nanmax(x)

2.0

In [46]:
np.nanmin(x)

0.0

In [47]:
np.nanmean(x),np.nanmedian(x)

(1.0, 1.0)

In [48]:
Data=pd.Series([10,20,30,np.nan,None])
Data

0    10.0
1    20.0
2    30.0
3     NaN
4     NaN
dtype: float64

In [49]:
Data.isnull()

0    False
1    False
2    False
3     True
4     True
dtype: bool

In [50]:
Data.isna()

0    False
1    False
2    False
3     True
4     True
dtype: bool

In [51]:
Data.notnull()

0     True
1     True
2     True
3    False
4    False
dtype: bool

In [58]:
Data.notna()

0       True
1       True
2       True
3      False
4      False
Age     True
dtype: bool

In [59]:
df=pd.DataFrame(Data)
df

0
0                      10
1                      20
2                      30
3                     NaN
4                     NaN
Age  [20, 30, 40, 50, 60]

In [61]:
df['Age']=np.array([20,30,40,50,60,10])
df['Gender']=np.array(['m','f','m','f','m','m'])
df

0  Age Gender
0                      10   20      m
1                      20   30      f
2                      30   40      m
3                     NaN   50      f
4                     NaN   60      m
Age  [20, 30, 40, 50, 60]   10      m

In [62]:
Data.notnull()

0       True
1       True
2       True
3      False
4      False
Age     True
dtype: bool

In [63]:
Data[Data.notnull()]

0                        10
1                        20
2                        30
Age    [20, 30, 40, 50, 60]
dtype: object

In [64]:
df[df[0].notnull()]

0  Age Gender
0                      10   20      m
1                      20   30      f
2                      30   40      m
Age  [20, 30, 40, 50, 60]   10      m

In [65]:
Data.fillna(value=2)

0                        10
1                        20
2                        30
3                         2
4                         2
Age    [20, 30, 40, 50, 60]
dtype: object

In [67]:
Data.fillna(value={1:60,2:100,5:50})

0                        10
1                        20
2                        30
3                       NaN
4                       NaN
Age    [20, 30, 40, 50, 60]
dtype: object

In [68]:
Df=pd.DataFrame([[1,np.nan,2,None],
                [2,3,5,10],
                [np.nan,4,9,15]],columns=['A','B','C','D'])
Df

A    B  C     D
0  1.0  NaN  2   NaN
1  2.0  3.0  5  10.0
2  NaN  4.0  9  15.0

In [69]:
Df.dropna() #by default you get row

A    B  C     D
1  2.0  3.0  5  10.0

In [70]:
Df.dropna(axis=1) #to columns

C
0  2
1  5
2  9

In [71]:
 Df.dropna(axis='rows')

A    B  C     D
1  2.0  3.0  5  10.0

In [72]:
Df['D']=np.nan
Df

A    B  C   D
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  9 NaN

In [73]:
Df.dropna(axis='columns',how='all')

A    B  C
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  9

In [74]:
Df.dropna(axis=1,how='all')

A    B  C
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  9

In [1]:
import pandas as pd
import numpy as np

In [2]:
data=pd.DataFrame(np.array([[np.nan,10,30,np.nan],
                           [20,9,30,np.nan],
                           [4,np.nan,40,70],
                           [5,20,np.nan,60]]),columns=['A','B','C','D'])
data

A     B     C     D
0   NaN  10.0  30.0   NaN
1  20.0   9.0  30.0   NaN
2   4.0   NaN  40.0  70.0
3   5.0  20.0   NaN  60.0

In [3]:
data.mean()

A     9.666667
B    13.000000
C    33.333333
D    65.000000
dtype: float64

In [4]:
data.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

In [5]:
data.isna()

A      B      C      D
0   True  False  False   True
1  False  False  False   True
2  False   True  False  False
3  False  False   True  False

In [6]:
data.isna().sum()

A    1
B    1
C    1
D    2
dtype: int64

In [7]:
for i in data.columns:
    fill=np.nanmean(data[i])
    print(fill)
    data[i].replace(np.nan,fill,inplace=True)
print(data)

9.666666666666666
13.0
33.333333333333336
65.0
           A     B          C     D
0   9.666667  10.0  30.000000  65.0
1  20.000000   9.0  30.000000  65.0
2   4.000000  13.0  40.000000  70.0
3   5.000000  20.0  33.333333  60.0


In [18]:
data

A     B     C     D
0   NaN  10.0  30.0   NaN
1  20.0   9.0  30.0   NaN
2   4.0   NaN  40.0  70.0
3   5.0  20.0   NaN  60.0

In [19]:
data.dropna(axis='rows',thresh=3)

A     B     C     D
1  20.0   9.0  30.0   NaN
2   4.0   NaN  40.0  70.0
3   5.0  20.0   NaN  60.0

In [21]:
data.dropna(axis='columns',thresh=3)

A     B     C
0   NaN  10.0  30.0
1  20.0   9.0  30.0
2   4.0   NaN  40.0
3   5.0  20.0   NaN

In [30]:
df=pd.DataFrame({'Int':[10,20,30,np.nan,50,60],
                'Float':[20.5,10.5,5.5,2.5,6.5,np.nan],
                'Complex':[np.nan,2j+3,np.nan,23j+2,5j+2,np.nan]
                })
df

Int  Float              Complex
0  10.0   20.5                  NaN
1  20.0   10.5   3.000000+2.000000j
2  30.0    5.5                  NaN
3   NaN    2.5  2.000000+23.000000j
4  50.0    6.5   2.000000+5.000000j
5  60.0    NaN                  NaN

In [31]:
df.isnull().sum()

Int        1
Float      1
Complex    3
dtype: int64

In [34]:
for i in df.columns:
    fill=np.nanmean(df[i])
    print(fill)
    df[i].replace(np.nan,fill,inplace=True)
print(df)

34.0
9.1
(2.333333333333333+10j)
    Int  Float              Complex
0  10.0   20.5  2.333333+10.000000j
1  20.0   10.5   3.000000+2.000000j
2  30.0    5.5  2.333333+10.000000j
3  34.0    2.5  2.000000+23.000000j
4  50.0    6.5   2.000000+5.000000j
5  60.0    9.1  2.333333+10.000000j
